.use-mongodb: &use-mongodb
  services:
    - name: khezen/mongo:3.4
      alias: mongo

before_script:
  - date

after_script:
  - date

stages:
  - test

test1:
  <<: *use-mongodb
  image: node:latest
  stage: test
  variables:
    CI_GITLAB: "true"
  cache:
    paths:
      - node_modules/
  before_script:
    - git submodule update --init --recursive
    - date
    - yarn install --silent
    - date
  script:
    - node --version
    - date
    - yarn test
  tags:
    - docker
    - gce
