testing:
  image: node:latest
  services:
    - name: khezen/mongo:3.4
      alias: mongo
  stage: test
  cache:
    paths:
      - node_modules/
  before_script:
    - git submodule update --init --recursive
    - npm i --silent
  script:
    - node --version
    - node test/index.js
  tags:
    - docker
    - gce
