#$Env:COMPOSE_CONVERT_WINDOWS_PATHS=1
version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  sut:
    image: j2m:latest
    build: .
    links:
      - mongo
    depends_on:
      - mongo